name: Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
      environment:
        description: 'Environment'
        required: false
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Run Go Mod Tidy
        run: |
          cd backend
          go mod tidy

      # - name: Bump version and tag
      #   id: bump_version
      #   run: |
      #     chmod +x .github/scripts/bump_version.sh
      #     .github/scripts/bump_version.sh

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}